name: Unit Tests
on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/NativeUnitTests.yml"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/NativeUnitTests.yml"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  repository_dispatch:
jobs:
  build:
    name: "Build for ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}
    env:
      BUILD_DIR: ${{ github.workspace }}/test/build
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Linux x86_64"
            os: "ubuntu-latest"
          - name: "macOS Universal"
            os: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Build Environment
        run: cmake -E make_directory ${{ env.BUILD_DIR }}
      - name: Running CMake
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake ..
      - name: Build Unit Tests
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build .
      - name: Run Unit Tests
        if: ${{ success() }}
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest
